<GlobalFunctions>
  <RetoolStorageQuery
    id="_GET_logo"
    actionType="read"
    fileId="64893029-7bf9-45df-858c-bdaa0789e788"
    isMultiplayerEdited={false}
    resourceDisplayName="retool_storage"
    resourceName="retool_storage"
    showFailureToaster={false}
    showSuccessToaster={false}
  />
</GlobalFunctions>
